include $(GOROOT)/src/Make.inc

TARG=github.com/ziutek/mymysql/native
GOFILES=\
	mysql.go\
	init.go\
	common.go\
	packet.go\
	codecs.go\
	errors.go\
	consts.go\
	command.go\
	result.go\
	addons.go\
	prepared.go\
	binding.go\
	unsafe.go\

include $(GOROOT)/src/Make.pkg
